development:
  adapter: postgresql
  encoding: unicode
  database: AncientSage_development
  pool: 5
  username: AncientSage
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: AncientSage_test
  pool: 5
  username: AncientSage
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: AncientSage_production
  pool: 5
  username: AncientSage
  password: